version: "2.1"
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - media

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Dublin
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_PATH}/Overseerr:/config
    restart: unless-stopped
    networks:
      - media

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
      - "8118:8118"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TIMEZONE}
      - VPN_ENABLED=false
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_CONF=wg0
      - VPN_ADDITIONAL_PORTS
      - PRIVOXY_ENABLED=false
    volumes:
      - ${CONFIG_PATH}/qbit:/config
      - ${DOWNLOADS_PATH}:/media/downloads
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - media

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MOVIES_PATH}:/media/movies 
      - ${DOWNLOADS_PATH}:/media/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - media

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1000:1000
    volumes:
      - ${CONFIG_PATH}/recyclarr:/config
    environment:
      - TZ=${TIMEZONE}
    networks:
      - media

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${TV_PATH}:/media/tv #optional
      - ${DOWNLOADS_PATH}:/media/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - media

  watchtower:
    image: containrrr/watchtower
    environment:
      - TZ=${TIMEZONE}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
    restart: unless-stopped    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  unpackerr:
    container_name: unpackerr
    image: ghcr.io/hotio/unpackerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/unpackerr:/config
    networks:
      - media
    security_opt:
      - no-new-privileges:true

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${CONFIG_PATH}/homarr/configs:/app/data/configs
      - ${CONFIG_PATH}/homarr/icons:/app/public/icons
      - ${CONFIG_PATH}/homarr/data:/data
    ports:
      - '7575:7575'
    networks:
      - media

networks:
  media:
    external: true
