version: "2.1"
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Dublin
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - media

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Dublin
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /configs/Overseerr:/config
    restart: unless-stopped
    networks:
      - media

  prowlmedia:
    image: lscr.io/linuxserver/prowlmedia:latest
    container_name: prowlmedia
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/Dublin
    volumes:
      - /configs/prowlmedia:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
      - "8118:8118"
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=Europe/Dublin
      - VPN_ENABLED=false
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_CONF=wg0
      - VPN_ADDITIONAL_PORTS
      - PRIVOXY_ENABLED=false
    volumes:
      - /configs/qbit:/config
      - /mnt/ext/Media/Downloads:/media/downloads
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - media

  radmedia:
    image: lscr.io/linuxserver/radmedia:latest
    container_name: radmedia
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/Dublin
    volumes:
      - /configs/radmedia:/config
      - /mnt/ext/Media/Movies:/media/movies 
      - /mnt/ext/Media/Downloads:/media/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - media

  recyclmedia:
    image: ghcr.io/recyclmedia/recyclmedia
    container_name: recyclmedia
    user: 568:568
    volumes:
      - /configs/recyclmedia:/config
    environment:
      - TZ=Europe/Dublin
    networks:
      - media

  sonmedia:
    image: lscr.io/linuxserver/sonmedia:latest
    container_name: sonmedia
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/Dublin
    volumes:
      - /configs/sonmedia:/config
      - /mnt/ext/Media/TVShows:/media/tv #optional
      - /mnt/ext/Media/Downloads:/media/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - media

  watchtower:
    image: containrrr/watchtower
    environment:
      - TZ=Europe/Dublin
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
    restart: unless-stopped    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  unpackerr:
    container_name: unpackerr
    image: ghcr.io/hotio/unpackerr
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=Europe/Dublin
    volumes:
      - /configs/unpackerr:/config
    networks:
      - media
    security_opt:
      - no-new-privileges:true

networks:
  media:
    external: true
